server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery: # 注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport: # sentinel端口号
        dashboard: localhost:8080
        port: 8719 # 和sentinel交互的端口号
  task:
    # Spring 执行器配置，对应 TaskExecutionProperties 配置类。对于 Spring 异步任务，会使用该执行器。
    execution:
      thread-name-prefix: task- # 线程池的线程名的前缀。默认为 task- ，建议根据自己应用来设置
      pool: # 线程池相关
        core-size: 8 # 核心线程数，线程池创建时候初始化的线程数。默认为 8 。
        max-size: 20 # 最大线程数，线程池最大的线程数，只有在缓冲队列满了之后，才会申请超过核心线程数的线程。默认为 Integer.MAX_VALUE
        keep-alive: 60s # 允许线程的空闲时间，当超过了核心线程之外的线程，在空闲时间到达之后会被销毁。默认为 60 秒
        queue-capacity: 200 # 缓冲队列大小，用来缓冲执行任务的队列的大小。默认为 Integer.MAX_VALUE 。
        allow-core-thread-timeout: true # 是否允许核心线程超时，即开启线程池的动态增长和缩小。默认为 true 。
      shutdown:
        await-termination: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
        await-termination-period: 60 # 等待任务完成的最大时长，单位为秒。默认为 0 ，根据自己应用来设置
  # rabbitmq相关配置
  rabbitmq:
    host: 192.168.61.130
    virtual-host: /gmall
    username: admin
    password: 123456
    listener:
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual
  # 数据库的相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.61.130:3306/guli_cart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  zipkin: # 链路追踪
    base-url: http://localhost:9411
    sender:
      type: web # 使用web的方式将链路追踪的消息传给zipkin
    discovery-client-enabled: false # 链路追踪自己不需要追踪自己
  sleuth:
    sampler: # 采集信息
      probability: 1 # 采集率默认为0.1，1表示百分之百采集率
  thymeleaf:
    cache: false
  redis:
    host: 192.168.61.130
feign: # 远程调用
  sentinel:
    enabled: true # 开启feign的sentinel的支持
logging:
  level: # 日志输出级别
    com.atguigu.gmall.cart: info
#Feign负载均衡配置 配置全局超时时间 毫秒单位
ribbon:
  ConnectTimeout: 50000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 50000 #请求处理的超时时间
mybatis-plus:
  global-config:
    db-config:
      id-type: auto # id自增长
# 配置公钥和私钥
auth:
  jwt:
    pubKeyPath: D:\\recv\\0325班\\rsa\\rsa.pub # 公钥
    cookieName: GMALL-TOKEN # cookie
    userkey: user-key
    expire: 31104000 # 设置有效时间单位秒
